# Generated by Django 5.0.7 on 2024-09-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_recipe_id", models.IntegerField()),
                ("recipe_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "user_recipe",
                "unique_together": {("user_id", "user_recipe_id")},
            },
        ),
    ]
