# Generated by Django 5.0.7 on 2024-09-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.IntegerField()),
                ("recipe_hash", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "user_recipe",
                "unique_together": {("account_id", "recipe_hash")},
            },
        ),
    ]
