# Generated by Django 5.0.7 on 2024-09-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_recipe', '0002_alter_userrecipe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipe',
            name='account_id',
            field=models.IntegerField(),
        ),
    ]
