# Generated by Django 5.0.7 on 2024-09-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_accountattendancecheck_attendance_date1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountattendancecheck",
            name="Attendance_last_login",
            field=models.IntegerField(default=0),
        ),
    ]
