# Generated by Django 5.0.7 on 2024-09-05 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_accountattendancecheck_attendance_last_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountattendancecheck",
            old_name="Attendance_last_login",
            new_name="Attendance_last_login_month",
        ),
    ]
