# Generated by Django 5.0.7 on 2024-09-05 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0004_rename_attendance_last_login_accountattendancecheck_attendance_last_login_month",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountattendancecheck",
            name="Attendance_last_login_month",
        ),
    ]
