# Generated by Django 5.0.7 on 2024-08-19 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTitle',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'recipe_title',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.TextField()),
                ('plate', models.IntegerField()),
                ('recipe_id', models.OneToOneField(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle')),
            ],
            options={
                'db_table': 'recipe_ingredient',
            },
        ),
        migrations.CreateModel(
            name='RecipeContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('recipe_id', models.OneToOneField(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle')),
            ],
            options={
                'db_table': 'recipe_content',
            },
        ),
    ]
