# Generated by Django 5.0.7 on 2024-08-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.CharField(max_length=500),
        ),
    ]
