# Generated by Django 5.0.7 on 2024-08-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=512)),
                ('recipe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle')),
            ],
            options={
                'db_table': 'recipe_content',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=64)),
                ('recipe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle')),
            ],
            options={
                'db_table': 'recipe_ingredient',
            },
        ),
    ]
