# Generated by Django 5.0.7 on 2024-08-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipecontent_recipeingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='recipe_id',
            field=models.OneToOneField(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_id',
            field=models.OneToOneField(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipetitle'),
        ),
    ]
