# Generated by Django 5.0.7 on 2024-08-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipeingredient_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
