# Generated by Django 5.0.7 on 2024-08-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipecontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.TextField(),
        ),
    ]
